// composables/useReportExport.ts
//
// Report export — renders a Markdown daily report, uploads to Lambda
// (or falls back to client‑side .md download).
//
// Replaces the old LaTeX pipeline. No Tectonic, no Unicode sanitisation —
// Markdown handles UTF‑8 natively.

import dayjs from 'dayjs'
import { useAuth } from '~/composables/useAuth'
import { useDataService } from '~/composables/useDataService'

// ── Markdown Template ────────────────────────────────────────────────────
const MD_TEMPLATE = `# Daily Focus Report — {{REPORT-DATE-FULL}}

**User:** {{USER-DISPLAY-NAME}}
**Email:** {{USER-EMAIL}}

## Summary

| Metric | Value |
|--------|-------|
| Total Focus Time | {{TOTAL-FOCUS-TIME}} min |
| Sessions | {{SESSIONS-COUNT}} |
| Tasks Completed | {{TASKS-COMPLETED}} / {{TASKS-TOTAL}} |
| Dominant Mood | {{DOMINANT-EMOTION}} |
| Streak | {{STREAK-DAYS}} days |

## Tasks

| Status | Task | Duration (min) |
|--------|------|----------------|
{{TASK-LIST-ROWS}}

## Mood & Insights

- **Peak Focus Hour:** {{PEAK-FOCUS-HOUR}}
- **Most Productive Day:** {{MOST-PRODUCTIVE-DAY}}
- **Longest Focus Streak:** {{LONGEST-STREAK}} min

> "{{MOOD-SUMMARY-TEXT}}"

## AI Suggestions

{{AI-SUGGESTIONS-BLOCK}}

## Recommended Content

{{RAG-RECOMMENDATIONS-BLOCK}}

---

Generated by Focus Mode App — {{APP-URL}}
`

// ── Composable ────────────────────────────────────────────────────────────
export function useReportExport() {
  const isExporting = ref(false)
  const exportError = ref<string | null>(null)
  const exportResult = ref<{ mdUrl?: string; pdfUrl?: string; message?: string } | null>(null)

  // ── Helpers (unchanged logic) ──────────────────────────────────────────
  function getDominantEmotion(sessions: any[]): string {
    if (sessions.length === 0) return 'none'
    const counts: Record<string, number> = {}
    for (const s of sessions) {
      if (s.emotionLabel) counts[s.emotionLabel] = (counts[s.emotionLabel] || 0) + 1
    }
    if (Object.keys(counts).length === 0) return 'none'
    return Object.entries(counts).sort((a, b) => b[1] - a[1])[0][0]
  }

  function getPeakFocusHour(sessions: any[]): string {
    if (sessions.length === 0) return 'N/A'
    const hours: Record<number, number> = {}
    for (const s of sessions) {
      const h = new Date(s.startTime).getHours()
      hours[h] = (hours[h] || 0) + 1
    }
    const peak = Object.entries(hours).sort((a, b) => b[1] - a[1])[0]
    return `${peak[0].toString().padStart(2, '0')}:00 (${peak[1]} sessions)`
  }

  function getMostProductiveDay(sessions: any[]): string {
    if (sessions.length === 0) return 'N/A'
    const days: Record<string, number> = {}
    for (const s of sessions) {
      const d = dayjs(s.startTime).format('dddd')
      days[d] = (days[d] || 0) + Math.round((s.durationActual ?? s.durationPlanned) / 60)
    }
    const best = Object.entries(days).sort((a, b) => b[1] - a[1])[0]
    return `${best[0]} (avg ${best[1]} min)`
  }

  function buildTaskRows(tasks: any[]): string {
    if (tasks.length === 0) return '| -- | No tasks recorded | -- |'
    return tasks.map(t => {
      const status = t.status === 'completed' ? 'completed' : t.status === 'in_progress' ? 'in progress' : 'pending'
      const duration = t.durationSpent || 0
      const title = (t.title || 'Untitled').replace(/\|/g, '\\|')
      return `| ${status} | ${title} | ${duration} |`
    }).join('\n')
  }

  function getLongestStreak(sessions: any[]): number {
    if (sessions.length === 0) return 0
    let streak = 0
    const dates = new Set(sessions.map((s: any) => dayjs(s.startTime).format('YYYY-MM-DD')))
    for (let i = 0; i < 365; i++) {
      if (dates.has(dayjs().subtract(i, 'day').format('YYYY-MM-DD'))) streak++
      else break
    }
    return streak
  }

  function getMoodSummary(dominant: string): string {
    const summaries: Record<string, string> = {
      focused: 'You maintained strong focus throughout the day.',
      stressed: 'You experienced some stress today. Consider taking breaks.',
      exhausted: 'You seemed tired today. Rest is important for productivity.',
      relaxed: 'You were in a relaxed state today. A balanced day.',
      unmotivated: 'Motivation was low today. Small wins can build momentum.',
      none: 'No mood data recorded today.',
    }
    return summaries[dominant] || summaries.none
  }

  async function exportReport(): Promise<void> {
    isExporting.value = true
    exportError.value = null
    exportResult.value = null

    try {
      const { currentUser } = useAuth()
      const { getTasks, getSessions } = useDataService()
      const today = dayjs().format('YYYY-MM-DD')

      // Gather data via the abstracted service
      const allTasks = await getTasks()
      const todayTasks = allTasks.filter(t => dayjs(t.createdAt).format('YYYY-MM-DD') === today)
      const allSessions = await getSessions()
      const todaySessions = allSessions.filter((s: any) => dayjs(s.startTime).format('YYYY-MM-DD') === today)

      const totalFocusTime = Math.round(
        todaySessions.reduce((sum: number, s: any) => sum + (s.durationActual ?? s.durationPlanned), 0) / 60,
      )
      const dominantEmotion = getDominantEmotion(todaySessions)

      const context: Record<string, string> = {
        'REPORT-DATE-FULL': dayjs().format('MMMM D, YYYY'),
        'USER-DISPLAY-NAME': currentUser.value?.name ?? currentUser.value?.email?.split('@')[0] ?? 'User',
        'USER-EMAIL': currentUser.value?.email ?? 'unknown@example.com',
        'TOTAL-FOCUS-TIME': String(totalFocusTime),
        'SESSIONS-COUNT': String(todaySessions.length),
        'TASKS-COMPLETED': String(todayTasks.filter(t => t.status === 'completed').length),
        'TASKS-TOTAL': String(todayTasks.length),
        'DOMINANT-EMOTION': dominantEmotion,
        'STREAK-DAYS': String(getLongestStreak(allSessions)),
        'TASK-LIST-ROWS': buildTaskRows(todayTasks),
        'PEAK-FOCUS-HOUR': getPeakFocusHour(todaySessions),
        'MOST-PRODUCTIVE-DAY': getMostProductiveDay(todaySessions),
        'LONGEST-STREAK': String(getLongestStreak(allSessions)),
        'MOOD-SUMMARY-TEXT': getMoodSummary(dominantEmotion),
        'AI-SUGGESTIONS-BLOCK': '- Schedule deep work during your peak focus hours.\n- Try 25/5 Pomodoro cycles for sustained concentration.',
        'RAG-RECOMMENDATIONS-BLOCK': '- **On Patience** (sutra) — Lamrim Class 2023\n- **5‑Minute Breathing** (video) — Self‑Help',
        'APP-URL': 'https://focusmode.app',
      }

      // Render Markdown
      let mdContent = MD_TEMPLATE
      for (const [key, value] of Object.entries(context)) {
        mdContent = mdContent.replaceAll(`{{${key}}}`, value)
      }

      // Try Lambda API first, fall back to .md download
      const config = useRuntimeConfig()
      const apiUrl = config.public.apiGatewayUrl as string

      if (apiUrl) {
        try {
          const response = await $fetch<{ markdown_url: string; pdf_url: string; message: string }>(
            `${apiUrl}/report`,
            { method: 'POST', body: { md_content: mdContent, user_id: currentUser.value?.id, date: today } },
          )
          exportResult.value = { mdUrl: response.markdown_url, pdfUrl: response.pdf_url, message: response.message }
          if (response.pdf_url) window.open(response.pdf_url, '_blank')
          return
        } catch { /* Lambda unavailable — fall through */ }
      }

      // Client-side fallback: download .md file
      const blob = new Blob([mdContent], { type: 'text/markdown' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `focus-report-${today}.md`
      a.click()
      URL.revokeObjectURL(url)
      exportResult.value = { message: 'Markdown report downloaded.' }
    } catch (e: any) {
      exportError.value = e?.message || 'Export failed'
    } finally {
      isExporting.value = false
    }
  }

  return { isExporting, exportError, exportResult, exportReport }
}
