// composables/useReportExport.ts
//
// Xuất báo cáo Markdown theo NGÀY — tải file .md ngay ở client (không gửi email,
// không gọi Lambda). Dùng ở dashboard (hôm nay) và Worklog History (từng ngày).
//
// Đã BỎ: gửi báo cáo qua email (deprecated), và 2 mục hardcode "AI Suggestions" +
// "Recommended Content" (không có AI thật — sẽ thay bằng vector-embedding gợi ý sau).

import dayjs from 'dayjs'
import { useAuth } from '~/composables/useAuth'
import { useDataService } from '~/composables/useDataService'

// ── Markdown Template (không còn mục AI Suggestions / Recommended Content) ────
const MD_TEMPLATE = `# Daily Focus Report — {{REPORT-DATE-FULL}}

**User:** {{USER-DISPLAY-NAME}}
**Email:** {{USER-EMAIL}}

## Summary

| Metric | Value |
|--------|-------|
| Total Focus Time | {{TOTAL-FOCUS-TIME}} min |
| Sessions | {{SESSIONS-COUNT}} |
| Tasks Completed | {{TASKS-COMPLETED}} / {{TASKS-TOTAL}} |
| Dominant Mood | {{DOMINANT-EMOTION}} |

## Tasks

| Status | Task | Priority | Duration (min) |
|--------|------|----------|----------------|
{{TASK-LIST-ROWS}}

## Mood & Insights

- **Peak Focus Hour:** {{PEAK-FOCUS-HOUR}}

> "{{MOOD-SUMMARY-TEXT}}"

{{JOURNAL-BLOCK}}
---

Generated by Focus Mode App — {{APP-URL}}
`

const PRIORITY_LABEL: Record<number, string> = { 0: '—', 1: 'Low', 2: 'Medium', 3: 'High' }

export function useReportExport() {
  const isExporting = ref(false)
  const exportError = ref<string | null>(null)
  const lastMessage = ref<string>('')

  function getDominantEmotion(sessions: any[]): string {
    const counts: Record<string, number> = {}
    for (const s of sessions) if (s.emotionLabel) counts[s.emotionLabel] = (counts[s.emotionLabel] || 0) + 1
    const top = Object.entries(counts).sort((a, b) => b[1] - a[1])[0]
    return top ? top[0] : 'none'
  }

  function getPeakFocusHour(sessions: any[]): string {
    if (sessions.length === 0) return 'N/A'
    const hours: Record<number, number> = {}
    for (const s of sessions) { const h = new Date(s.startTime).getHours(); hours[h] = (hours[h] || 0) + 1 }
    const peak = Object.entries(hours).sort((a, b) => b[1] - a[1])[0]
    return `${peak[0].toString().padStart(2, '0')}:00 (${peak[1]} sessions)`
  }

  function buildTaskRows(tasks: any[]): string {
    if (tasks.length === 0) return '| -- | No tasks recorded | -- | -- |'
    return tasks.map((t) => {
      const status = t.status === 'completed' ? 'completed' : t.status === 'in_progress' ? 'in progress' : t.status
      const title = (t.title || 'Untitled').replace(/\|/g, '\\|')
      const prio = PRIORITY_LABEL[t.priority || 0] || '—'
      return `| ${status} | ${title} | ${prio} | ${t.durationSpent || 0} |`
    }).join('\n')
  }

  function getMoodSummary(dominant: string): string {
    const s: Record<string, string> = {
      focused: 'You maintained strong focus throughout the day.',
      stressed: 'You experienced some stress today. Consider taking breaks.',
      exhausted: 'You seemed tired today. Rest is important for productivity.',
      relaxed: 'You were in a relaxed state today. A balanced day.',
      unmotivated: 'Motivation was low today. Small wins can build momentum.',
      none: 'No mood data recorded for this day.',
    }
    return s[dominant] || s.none
  }

  function buildJournalBlock(sessions: any[]): string {
    const entries = sessions.filter(s => s.journalText)
    if (entries.length === 0) return ''
    const lines = entries.map(s => `- "${s.journalText}"${s.emotionLabel ? ` _(${s.emotionLabel})_` : ''}`).join('\n')
    return `## Journal Entries\n\n${lines}\n\n`
  }

  // dateStr = 'YYYY-MM-DD'; mặc định hôm nay. Tải .md của đúng ngày đó.
  async function downloadReport(dateStr?: string): Promise<void> {
    isExporting.value = true
    exportError.value = null
    lastMessage.value = ''
    try {
      const { currentUser } = useAuth()
      const { getTasks, getSessions } = useDataService()
      const date = dateStr || dayjs().format('YYYY-MM-DD')

      const allTasks = await getTasks()
      const allSessions = await getSessions()
      const daySessions = allSessions.filter((s: any) => dayjs(s.startTime).format('YYYY-MM-DD') === date)
      const dayTasks = allTasks.filter((t: any) =>
        dayjs(t.createdAt).format('YYYY-MM-DD') === date ||
        (t.completedAt && dayjs(t.completedAt).format('YYYY-MM-DD') === date))

      const totalFocusTime = Math.round(daySessions.reduce((sum: number, s: any) => sum + (s.durationActual ?? s.durationPlanned ?? 0), 0) / 60)
      const dominant = getDominantEmotion(daySessions)

      const ctx: Record<string, string> = {
        'REPORT-DATE-FULL': dayjs(date).format('dddd, MMMM D, YYYY'),
        'USER-DISPLAY-NAME': currentUser.value?.name ?? currentUser.value?.email?.split('@')[0] ?? 'User',
        'USER-EMAIL': currentUser.value?.email ?? 'unknown@example.com',
        'TOTAL-FOCUS-TIME': String(totalFocusTime),
        'SESSIONS-COUNT': String(daySessions.length),
        'TASKS-COMPLETED': String(dayTasks.filter((t: any) => t.status === 'completed').length),
        'TASKS-TOTAL': String(dayTasks.length),
        'DOMINANT-EMOTION': dominant,
        'TASK-LIST-ROWS': buildTaskRows(dayTasks),
        'PEAK-FOCUS-HOUR': getPeakFocusHour(daySessions),
        'MOOD-SUMMARY-TEXT': getMoodSummary(dominant),
        'JOURNAL-BLOCK': buildJournalBlock(daySessions),
        'APP-URL': 'https://focusmode.click',
      }

      let md = MD_TEMPLATE
      for (const [k, v] of Object.entries(ctx)) md = md.replaceAll(`{{${k}}}`, v)

      const blob = new Blob([md], { type: 'text/markdown' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `focus-report-${date}.md`
      a.click()
      URL.revokeObjectURL(url)
      lastMessage.value = `Đã tải báo cáo ${date}.md`
    } catch (e: any) {
      exportError.value = e?.message || 'Export failed'
    } finally {
      isExporting.value = false
    }
  }

  return { isExporting, exportError, lastMessage, downloadReport }
}
